steps:
- name: 'python:3.11'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      pip install dvc[all]
- name: 'python:3.9'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      dvc pull
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/mlops60-448009/mlopsgroup60/mlopsgroup60',
    '-f',
    'dockerfiles/train.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/mlops60-448009/mlopsgroup60/mlopsgroup60'
  ]
options:
  logging: CLOUD_LOGGING_ONLY
