steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/mlops60-448009/mlopsgroup60/mlopsapi',
    '-f',
    'dockerfiles/api.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/mlops60-448009/mlopsgroup60/mlopsapi'
  ]
options:
  logging: CLOUD_LOGGING_ONLY
